/*Write a C program that will create a child process to generate a Fibonacci series of specified
length and store it in an array. The parent process will wait for the child to complete its task
and then display the Fibonacci series and then display the prime Fibonacci number in the
series along with its position with appropriate message*/
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <stdbool.h>

// Function to check if a number is prime
bool is_prime(int num) {
    if (num <= 1) {
        return false;
    }
    for (int i = 2; i * i <= num; i++) {
        if (num % i == 0) {
            return false;
        }
    }
    return true;
}

// Function to generate Fibonacci series
void generate_fibonacci(int n, int *fib) {
    fib[0] = 0;
    if (n > 1) {
        fib[1] = 1;
    }

    for (int i = 2; i < n; i++) {
        fib[i] = fib[i - 1] + fib[i - 2];
    }

    // Print Fibonacci series (child process will do this)
    printf("Fibonacci Series: ");
    for (int i = 0; i < n; i++) {
        printf("%d ", fib[i]);
    }
    printf("\n");
}

int main() {
    int n;
    printf("Enter the length of the Fibonacci series: ");
    scanf("%d", &n);

    // Check for valid input
    if (n <= 0) {
        printf("Please enter a positive number for the length of the series.\n");
        return 1;
    }

    pid_t pid = fork();
    if (pid < 0) {
        perror("Fork failed");
        return 1;
    }

    if (pid == 0) {
        // Child process: Generate Fibonacci series and store in an array
        int fib[n];
        generate_fibonacci(n, fib);
        exit(0);  // Child process exits after completing the task
    } else {
        // Parent process: Wait for the child process to finish
        wait(NULL);

        // Parent process continues after child completes
        int fib[n];
        generate_fibonacci(n, fib);

        // Display prime Fibonacci numbers and their positions
        printf("Prime Fibonacci numbers in the series with their positions:\n");
        for (int i = 0; i < n; i++) {
            if (is_prime(fib[i])) {
                printf("Position %d: %d is a prime number.\n", i + 1, fib[i]);
            }
        }

        printf("Parent (PID: %d) has completed its task.\n", getpid());
    }

    return 0;
}
/*Prime Checking Function (is_prime):

    This function checks whether a given number is prime. It returns true if the number is prime, and false otherwise.
    It handles edge cases like numbers less than or equal to 1 and checks for divisibility up to the square root of the number.

Fibonacci Generation (generate_fibonacci):

    This function generates the Fibonacci series and stores it in an array. The Fibonacci series is generated by the formula:
        fib[i] = fib[i - 1] + fib[i - 2]
    The series is printed by the child process when it completes the task.

Forking the Process:

    The fork() system call creates a new child process.
    The child process generates the Fibonacci series and exits after completing its task.
    The parent process waits for the child to complete using wait(NULL) and then prints the Fibonacci series and identifies the prime numbers in the series.

Parent Process Behavior:

    After the child process finishes its task, the parent process generates the Fibonacci series again (this could be optimized, but it's done here for simplicity).
    The parent process identifies and displays the prime Fibonacci numbers along with their positions.*/